export const acrossPortalAbi = [
    {
        inputs: [
            { internalType: "address", name: "_superSwapAddr", type: "address" },
            { internalType: "address", name: "_spokePoolAddr", type: "address" },
            { internalType: "address", name: "_weth", type: "address" },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "previousOwner",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        inputs: [],
        name: "WETH",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "tokenSent", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "address", name: "relayer", type: "address" },
            { internalType: "bytes", name: "message", type: "bytes" },
        ],
        name: "handleV3AcrossMessage",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "address", name: "tokenIn", type: "address" },
                    { internalType: "uint256", name: "amountIn", type: "uint256" },
                    { internalType: "address", name: "tokenOut", type: "address" },
                    { internalType: "uint256", name: "amountOutMin", type: "uint256" },
                    { internalType: "bytes", name: "routeCode", type: "bytes" },
                ],
                internalType: "struct SuperSwapPortal.OriginalSideSwapData",
                name: "originalData",
                type: "tuple",
            },
            {
                components: [
                    { internalType: "bytes32", name: "depositor", type: "bytes32" },
                    { internalType: "bytes32", name: "recipient", type: "bytes32" },
                    { internalType: "bytes32", name: "inputToken", type: "bytes32" },
                    { internalType: "bytes32", name: "outputToken", type: "bytes32" },
                    { internalType: "uint256", name: "inputAmount", type: "uint256" },
                    { internalType: "uint256", name: "outputAmount", type: "uint256" },
                    {
                        internalType: "uint256",
                        name: "destinationChainId",
                        type: "uint256",
                    },
                    {
                        internalType: "bytes32",
                        name: "exclusiveRelayer",
                        type: "bytes32",
                    },
                    { internalType: "uint32", name: "quoteTimestamp", type: "uint32" },
                    { internalType: "uint32", name: "fillDeadline", type: "uint32" },
                    {
                        internalType: "uint32",
                        name: "exclusivityDeadline",
                        type: "uint32",
                    },
                    { internalType: "bytes", name: "message", type: "bytes" },
                ],
                internalType: "struct SuperSwapPortal.SpokePoolDepositData",
                name: "spokePoolData",
                type: "tuple",
            },
        ],
        name: "sendSwapRequest",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "_superSwapAddr", type: "address" },
            { internalType: "address", name: "_spokePoolAddr", type: "address" },
        ],
        name: "setAddresses",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "spokePoolAddress",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "superSwapAddress",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
        name: "transferOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "token", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        name: "withdrawTokens",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    { stateMutability: "payable", type: "receive" },
] as const
