import { ChainId } from "@/packages/chain";
import Ink from "@/assets/network/ink.png";

export const DEFAULT_IMAGE_URL = "/media/unknown.svg";

export const NATIVE_GAS_FEE = 1000000000000000n;

export const SWAP_FEE = 0n;

export const ACROSS_ESTIMATED_TIME = {
  [ChainId.ETHEREUM]: {
    [ChainId.OP]: 21,
    [ChainId.UNICHAIN]: 19,
    [ChainId.POLYGON]: 22,
    // [ChainId.ZKSYNC]: 19,
    [ChainId.WORLDCHAIN]: 31,
    [ChainId.SONEIUM]: 19,
    [ChainId.BASE]: 21,
    [ChainId.ARBITRUM]: 21,
    [ChainId.INK]: 31,
    [ChainId.LINEA]: 19,
    [ChainId.ZORA]: 31,
  },
  [ChainId.OP]: {
    [ChainId.ETHEREUM]: 9,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 8,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 5,
    [ChainId.BASE]: 4,
    [ChainId.ARBITRUM]: 4,
    [ChainId.INK]: 5,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.UNICHAIN]: {
    [ChainId.ETHEREUM]: 9,
    [ChainId.OP]: 3,
    [ChainId.POLYGON]: 8,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 5,
    [ChainId.BASE]: 3,
    [ChainId.ARBITRUM]: 3,
    [ChainId.INK]: 5,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.POLYGON]: {
    [ChainId.ETHEREUM]: 41,
    [ChainId.OP]: 43,
    [ChainId.UNICHAIN]: 43,
    // [ChainId.ZKSYNC]: 46,
    [ChainId.WORLDCHAIN]: 46,
    [ChainId.SONEIUM]: 46,
    [ChainId.BASE]: 43,
    [ChainId.ARBITRUM]: 43,
    [ChainId.INK]: 46,
    [ChainId.LINEA]: 46,
    [ChainId.ZORA]: 46,
  },
  // [ChainId.ZKSYNC]: {
  //   [ChainId.ETHEREUM]: 9,
  //   [ChainId.OP]: 3,
  //   [ChainId.UNICHAIN]: 3,
  //   [ChainId.POLYGON]: 6,
  //   [ChainId.WORLDCHAIN]: 5,
  //   [ChainId.SONEIUM]: 5,
  //   [ChainId.BASE]: 3,
  //   [ChainId.ARBITRUM]: 3,
  //   [ChainId.INK]: 5,
  //   [ChainId.LINEA]: 3,
  //   [ChainId.ZORA]: 5,
  // },
  [ChainId.WORLDCHAIN]: {
    [ChainId.ETHEREUM]: 11,
    [ChainId.OP]: 3,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 9,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.SONEIUM]: 5,
    [ChainId.BASE]: 3,
    [ChainId.ARBITRUM]: 3,
    [ChainId.INK]: 5,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.SONEIUM]: {
    [ChainId.ETHEREUM]: 9,
    [ChainId.OP]: 3,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 7,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.BASE]: 3,
    [ChainId.ARBITRUM]: 3,
    [ChainId.INK]: 6,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.BASE]: {
    [ChainId.ETHEREUM]: 9,
    [ChainId.OP]: 4,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 8,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 5,
    [ChainId.ARBITRUM]: 4,
    [ChainId.INK]: 5,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.ARBITRUM]: {
    [ChainId.ETHEREUM]: 9,
    [ChainId.OP]: 4,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 8,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 5,
    [ChainId.BASE]: 4,
    [ChainId.INK]: 5,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.INK]: {
    [ChainId.ETHEREUM]: 11,
    [ChainId.OP]: 3,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 9,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 6,
    [ChainId.BASE]: 3,
    [ChainId.ARBITRUM]: 4,
    [ChainId.LINEA]: 3,
    [ChainId.ZORA]: 5,
  },
  [ChainId.LINEA]: {
    [ChainId.ETHEREUM]: 9,
    [ChainId.OP]: 3,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 6,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 5,
    [ChainId.BASE]: 3,
    [ChainId.ARBITRUM]: 3,
    [ChainId.INK]: 5,
    [ChainId.ZORA]: 5,
  },
  [ChainId.ZORA]: {
    [ChainId.ETHEREUM]: 11,
    [ChainId.OP]: 3,
    [ChainId.UNICHAIN]: 3,
    [ChainId.POLYGON]: 9,
    // [ChainId.ZKSYNC]: 3,
    [ChainId.WORLDCHAIN]: 5,
    [ChainId.SONEIUM]: 5,
    [ChainId.BASE]: 3,
    [ChainId.ARBITRUM]: 3,
    [ChainId.INK]: 5,
    [ChainId.LINEA]: 3,
  },
};
